-- Parameters:
--   product_id, product_run_id, product_time_id, product_field_id,
--   vertical_level_id, asset_role, relative_path, mime_type, file_size_bytes,
--   sha256, projection, bounds_wkt, width, height, band_count, nodata_value,
--   minimum_value, maximum_value, statistics, provenance, status
INSERT INTO catalogue.asset (
    product_id,
    product_run_id,
    product_time_id,
    product_field_id,
    vertical_level_id,
    asset_role,
    storage_backend,
    relative_path,
    mime_type,
    file_size_bytes,
    sha256,
    projection,
    bounds,
    width,
    height,
    band_count,
    nodata_value,
    minimum_value,
    maximum_value,
    statistics,
    provenance,
    status
)
VALUES (
    %(product_id)s,
    %(product_run_id)s,
    %(product_time_id)s,
    %(product_field_id)s,
    %(vertical_level_id)s,
    %(asset_role)s,
    'local',
    %(relative_path)s,
    %(mime_type)s,
    %(file_size_bytes)s,
    %(sha256)s,
    %(projection)s,
    ST_GeomFromText(%(bounds_wkt)s, 4326)::geometry(Polygon, 4326),
    %(width)s,
    %(height)s,
    %(band_count)s,
    %(nodata_value)s,
    %(minimum_value)s,
    %(maximum_value)s,
    %(statistics)s,
    %(provenance)s,
    %(status)s
)
ON CONFLICT (
    product_run_id,
    product_time_id,
    product_field_id,
    vertical_level_id,
    asset_role
) DO UPDATE
SET relative_path = EXCLUDED.relative_path,
    mime_type = EXCLUDED.mime_type,
    file_size_bytes = EXCLUDED.file_size_bytes,
    sha256 = EXCLUDED.sha256,
    projection = EXCLUDED.projection,
    bounds = EXCLUDED.bounds,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    band_count = EXCLUDED.band_count,
    nodata_value = EXCLUDED.nodata_value,
    minimum_value = EXCLUDED.minimum_value,
    maximum_value = EXCLUDED.maximum_value,
    statistics = EXCLUDED.statistics,
    provenance = EXCLUDED.provenance,
    status = EXCLUDED.status,
    updated_at = clock_timestamp()
RETURNING
    id,
    product_id,
    product_run_id,
    product_time_id,
    product_field_id,
    vertical_level_id,
    asset_role,
    storage_backend,
    relative_path,
    mime_type,
    file_size_bytes,
    sha256,
    projection,
    ST_AsGeoJSON(bounds)::jsonb AS bounds,
    width,
    height,
    band_count,
    nodata_value,
    minimum_value,
    maximum_value,
    statistics,
    provenance,
    status,
    created_at,
    updated_at;
